set_property IOSTANDARD LVCMOS33 [get_ports gpio_in1]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_in2]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_in3]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_in4]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN T9 [get_ports gpio_in1]
set_property PACKAGE_PIN T8 [get_ports gpio_in2]
set_property PACKAGE_PIN T7 [get_ports gpio_in3]
set_property PACKAGE_PIN T7 [get_ports gpio_in4]
set_property PACKAGE_PIN D4 [get_ports sys_clk]

set_property IOSTANDARD LVCMOS33 [get_ports pwm_1]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_2]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_3]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_4]
set_property PACKAGE_PIN A2 [get_ports pwm_1]
set_property PACKAGE_PIN B1 [get_ports pwm_2]
set_property PACKAGE_PIN C2 [get_ports pwm_3]
set_property PACKAGE_PIN D1 [get_ports pwm_4]

set_property PACKAGE_PIN P6 [get_ports gpio_in31]
set_property PACKAGE_PIN R6 [get_ports gpio_in32]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_in31]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_in32]

